name: Deploy to GitHub Pages - 001

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'  # Change this to match your desired .NET Core version

    - name: Build and publish
      run: |
        dotnet build -c Release
        dotnet publish -c Release -o publish

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.2.0
      with:
        branch: gh-pages
        folder: publish  # Change this to the folder where your published files are located

    - name: Deploy project URL to gh-pages
      run: |
        echo "::set-env name=PROJECT_URL::Blazor-01/MVC-07/MVC-07.csproj"
        echo "The project URL is $PROJECT_URL"
