name: GitHub Pages - MVC7.0
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: Build and publish
        run: |
          dotnet restore
          dotnet build MVC-07 --configuration Release
          dotnet publish MVC-07 -c Release -o ./publish

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ./publish  # Adjust this path if your static files are in a different folder
          BUILD_SCRIPT: dotnet publish MVC-07/publish -c Release -o ./
