name: GitHub Pages - MVC7.0
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build MVC-07 --configuration Release

    - name: Test
      run: dotnet test

    - name: Publish
      run: dotnet publish MVC-07/MVC-07.csproj -c Release -o ./publish

    - name: Deploy to GP
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: main # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: ./ # The folder the action should deploy.
        SINGLE_COMMIT: true
